### ISSUE TITLE
GoogleSignInResult result.isSuccess() return false

### ISSUE THREAD

**Issue by grovertb** [mugan86/firebase-login-google-android#1]
Hi, I'm having problems when trying to log example answers in the "result.isSuccess()" false, as I can fix it?
Thank you

**Comment by mugan86** [comment]
@grovertb good afternoon friend, you tried to set everything as it comes in reference https://firebase.google.com/docs/auth/android/google-signin? 

I have not created the README with instructions (which I have to do without fail) but you have to make the necessary settings in Firebase to access Google account by Firebase.

You have to generate your file "google-services.json" with the reference that I have provided and then replaced. You have to see that you are using a different SHA and does not give you access and therefore gives a value "false".
Tests and tell me and if not itemize me a little more if you set all of that reference and see if we can do something. 

Regards!
